#include "DivideByZeroException.hpp"
#include "NegativeSqrtException.hpp"
#include "InvalidAccessArgumentException.hpp"
#include "FloatTypeGivenException.hpp"
#include "NumberTooLargeException.hpp"
#include "DigitsTooLargeException.hpp"