name: Build and run tests

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

env:
  TARGET: Arkulib_tests

jobs:
  Linux_GCC_Debug:
    name: Linux GCC Debug
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure CMake
        run: cmake ./ -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=Debug -D CMAKE_C_COMPILER=gcc-11 -D CMAKE_CXX_COMPILER=g++-11

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Debug --target ${{env.TARGET}}

      - name: Run
        run: ${{github.workspace}}/build/tests/${{env.TARGET}}

  MacOS_Clang_Debug:
    name: MacOS Clang Debug
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake ./ -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=Debug -D CMAKE_C_COMPILER=$(brew --prefix llvm@14)/bin/clang -D CMAKE_CXX_COMPILER=$(brew --prefix llvm@14)/bin/clang++

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Debug --target ${{env.TARGET}}

      - name: Run
        run: ${{github.workspace}}/build/tests/${{env.TARGET}}